# Generated by Django 5.2.5 on 2025-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='art_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bank',
            name='gas_station_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bank',
            name='hotel_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bank',
            name='music_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bank',
            name='pharmacy_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bank',
            name='transaction_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='statement',
            name='pars',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
